import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Benji - AppCubic",
  description: "Generated by AppCubic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-zinc-900 text-slate-200">
      <body className={urbanist.className}>
        <Header />
        {children}
        <div className="h-[400vh]"></div>
        <Footer />
      </body>
    </html>
  );
}
